class Status:
    STATUS1 = "EXECUTION NOT STARTED YET"
    STATUS2 = "SEARCHING BY MOBILE BRANDS STARTED"
    STATUS3 = "SEARCHING BY MOBILE NAME STARTED"
    STATUS4 = "FETCHING PROXIES FOR SMOOTH SCRAPING"
    STATUS5 = "PROXIES FETCHED SUCCESSFULLY"
    STATUS6 = "EXECUTION STARTED"
    STATUS7 = "STARTED SCRAPPING MOBILE BRAND: '{0}'"
    STATUS8 = "SCRAPPED MOBILE BRAND: '{0}' SUCCESSFULLY"
    STATUS9 = "NAVIGATED TO WEBSITE: '{0}'"
    STATUS10 = "SUCCESSFULLY SCRAPPED THE MOBILES BY BRANDS!!!"
    STATUS11 = "SEARCHING BY MOBILE NAME: '{0}' STARTED"
    STATUS12 = "MOBILE FOUND: '{0}'"
    STATUS13 = "STARTED SCRAPPING MOBILE: '{0}' SPECS"
    STATUS14 = "SUCCESSFULLY SCRAPPED: '{0}' MOBILE SPECS"
    STATUS15 = "STARTED PREPARING DATA TO EXPORT"
    STATUS16 = "FILE EXPORTED SUCCESSFULLY!!!"

class Warning:
    WARNING1 = "KINDLY SELECT ANY 1 OF THE CHECKBOX"
    WARNING2 = "KINDLY FILL THE TEXTFIELD"
    WARNING3 = "NO MOBILE FOUND, KINDLY VERIFY THE NAME"
    WARNING4 = "UNABLE TO FETCH MOBILE SPECS DUE TO UNEXPECTED ERROR"
    WARNING5 = "UNABLE TO FIND MOBILE SPECS TABLE"

class Error:
    ERROR1 = "UNEXPECTED ERROR OCCUR, TRY AGAIN"
    ERROR2 = "UNABLE TO FETCH PROXIES"